### ISSUE TITLE
Installation fails due to missing `docs/CHANGES.rst` on PyPI

### ISSUE THREAD

**Issue by coddingtonbear** [romanofski/programslice#25]
```
Collecting programslice
  Downloading programslice-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-yZOSg_/programslice/setup.py", line 19, in <module>
        open('docs/CHANGES.rst').read()
    IOError: [Errno 2] No such file or directory: 'docs/CHANGES.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-yZOSg_/programslice/
```

I've worked around this by just installing from the github repository directly, but the above will be a problem for anybody installing from PyPI.

You might want to check out [https://github.com/mgedmin/check-manifest](https://github.com/mgedmin/check-manifest) by the way, for avoiding this sort of thing in the future; I break that sort of thing all the time, myself!

**Comment by romanofski** [comment]
Many thanks for the bug report. I haven't worked on the tool for quite a while and therefore never realised that the release was botched.
